// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/background.js"
    | "/content-scripts/content.js"
    | "/edit_pen_48.png"
    | "/gear_128.png"
    | "/mustard_bottle_smile_128.png"
    | "/mustard_bottle_smile_16.png"
    | "/mustard_bottle_smile_32.png"
    | "/mustard_bottle_smile_48.png"
    | "/mustard_bottle_smile_512.png"
    | "/options.html"
    | "/popup.html"
    | "/url-change-detector.js"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
