/** One row per visible emoji; first name is canonical, the rest are searchable aliases. */
export const EMOJI_CATALOGUE: ReadonlyArray<{ emoji: string; names: readonly string[] }> = [
  { emoji: '👍', names: ['thumbs-up', 'plus-one', 'like'] },
  { emoji: '👎', names: ['thumbs-down', 'minus-one', 'dislike'] },
  { emoji: '😄', names: ['smile'] },
  { emoji: '😃', names: ['smiley'] },
  { emoji: '😊', names: ['smiling', 'blush'] },
  { emoji: '😁', names: ['grin'] },
  { emoji: '😀', names: ['grinning'] },
  { emoji: '😂', names: ['joy', 'laughing-tears'] },
  { emoji: '😆', names: ['laughing'] },
  { emoji: '😉', names: ['wink'] },
  { emoji: '😌', names: ['relieved'] },
  { emoji: '😪', names: ['sleepy'] },
  { emoji: '😴', names: ['sleeping'] },
  { emoji: '🥱', names: ['yawning'] },
  { emoji: '😐', names: ['neutral'] },
  { emoji: '😑', names: ['expressionless'] },
  { emoji: '😕', names: ['confused'] },
  { emoji: '😟', names: ['worried'] },
  { emoji: '🥺', names: ['pleading'] },
  { emoji: '😵', names: ['dizzy'] },
  { emoji: '🤢', names: ['sick'] },
  { emoji: '🤧', names: ['sneezing'] },
  { emoji: '😷', names: ['mask'] },
  { emoji: '🤓', names: ['nerd'] },
  { emoji: '🥳', names: ['party', 'party-face'] },
  { emoji: '😘', names: ['kiss'] },
  { emoji: '🤗', names: ['hug'] },
  { emoji: '❤️', names: ['heart', 'red-heart'] },
  { emoji: '💔', names: ['broken-heart'] },
  { emoji: '🧡', names: ['orange-heart'] },
  { emoji: '💛', names: ['yellow-heart'] },
  { emoji: '💚', names: ['green-heart'] },
  { emoji: '💙', names: ['blue-heart'] },
  { emoji: '💜', names: ['purple-heart'] },
  { emoji: '🖤', names: ['black-heart'] },
  { emoji: '🤍', names: ['white-heart'] },
  { emoji: '😍', names: ['heart-eyes'] },
  { emoji: '🫶', names: ['heart-hands'] },
  { emoji: '🔥', names: ['fire', 'flame'] },
  { emoji: '🎉', names: ['tada', 'party-popper'] },
  { emoji: '👏', names: ['clap', 'applause'] },
  { emoji: '👋', names: ['wave', 'hello'] },
  { emoji: '👌', names: ['ok-hand'] },
  { emoji: '🙌', names: ['raised-hands'] },
  { emoji: '👊', names: ['fist-bump'] },
  { emoji: '🤞', names: ['crossed-fingers'] },
  { emoji: '👆', names: ['point-up'] },
  { emoji: '👇', names: ['point-down'] },
  { emoji: '👈', names: ['point-left'] },
  { emoji: '👉', names: ['point-right'] },
  { emoji: '🖕', names: ['middle-finger'] },
  { emoji: '💪', names: ['muscle', 'strong'] },
  { emoji: '🤝', names: ['handshake'] },
  { emoji: '🫡', names: ['salute'] },
  { emoji: '🙏', names: ['pray', 'thanks'] },
  { emoji: '🤔', names: ['thinking'] },
  { emoji: '👀', names: ['eyes', 'looking'] },
  { emoji: '🙈', names: ['see-no-evil', 'monkey-see-no-evil'] },
  { emoji: '🙉', names: ['hear-no-evil', 'monkey-hear-no-evil'] },
  { emoji: '🙊', names: ['speak-no-evil', 'monkey-speak-no-evil'] },
  { emoji: '😢', names: ['cry', 'sad'] },
  { emoji: '😭', names: ['sob'] },
  { emoji: '😠', names: ['angry'] },
  { emoji: '😡', names: ['rage'] },
  { emoji: '😱', names: ['scream'] },
  { emoji: '😮', names: ['surprised'] },
  { emoji: '😎', names: ['cool'] },
  { emoji: '⭐', names: ['star'] },
  { emoji: '🤩', names: ['star-struck'] },
  { emoji: '☀️', names: ['sun'] },
  { emoji: '🌙', names: ['moon'] },
  { emoji: '🌈', names: ['rainbow'] },
  { emoji: '☁️', names: ['cloud'] },
  { emoji: '❄️', names: ['snowflake'] },
  { emoji: '⚡', names: ['lightning'] },
  { emoji: '🌧️', names: ['rain'] },
  { emoji: '☂️', names: ['umbrella'] },
  { emoji: '✅', names: ['check', 'done'] },
  { emoji: '❌', names: ['x', 'cross'] },
  { emoji: '⚠️', names: ['warning'] },
  { emoji: '❓', names: ['question'] },
  { emoji: '❗', names: ['exclamation'] },
  { emoji: '🚀', names: ['rocket'] },
  { emoji: '✨', names: ['sparkles'] },
  { emoji: '💡', names: ['bulb', 'idea'] },
  { emoji: '💯', names: ['hundred'] },
  { emoji: '🎊', names: ['confetti'] },
  { emoji: '🎈', names: ['balloon'] },
  { emoji: '🎁', names: ['gift'] },
  { emoji: '🏆', names: ['trophy'] },
  { emoji: '🏅', names: ['medal'] },
  { emoji: '⚽', names: ['soccer'] },
  { emoji: '🏀', names: ['basketball'] },
  { emoji: '🎵', names: ['music'] },
  { emoji: '🎤', names: ['microphone'] },
  { emoji: '🎸', names: ['guitar'] },
  { emoji: '🎮', names: ['gamepad', 'gaming'] },
  { emoji: '📷', names: ['camera'] },
  { emoji: '💻', names: ['computer', 'laptop'] },
  { emoji: '📱', names: ['phone'] },
  { emoji: '📧', names: ['email'] },
  { emoji: '📖', names: ['book'] },
  { emoji: '✏️', names: ['pencil'] },
  { emoji: '📌', names: ['pin'] },
  { emoji: '🔗', names: ['link'] },
  { emoji: '🔒', names: ['lock'] },
  { emoji: '🔑', names: ['key'] },
  { emoji: '💰', names: ['money'] },
  { emoji: '💎', names: ['gem'] },
  { emoji: '🕒', names: ['clock'] },
  { emoji: '☕', names: ['coffee'] },
  { emoji: '🍵', names: ['tea'] },
  { emoji: '🍕', names: ['pizza'] },
  { emoji: '🍔', names: ['burger'] },
  { emoji: '🍟', names: ['fries'] },
  { emoji: '🌮', names: ['taco'] },
  { emoji: '🍣', names: ['sushi'] },
  { emoji: '🎂', names: ['cake', 'birthday'] },
  { emoji: '🍪', names: ['cookie'] },
  { emoji: '🍎', names: ['apple'] },
  { emoji: '🍌', names: ['banana'] },
  { emoji: '🥑', names: ['avocado'] },
  { emoji: '🍺', names: ['beer'] },
  { emoji: '🍷', names: ['wine'] },
  { emoji: '🐱', names: ['cat'] },
  { emoji: '🐶', names: ['dog'] },
  { emoji: '🦊', names: ['fox'] },
  { emoji: '🐻', names: ['bear'] },
  { emoji: '🐼', names: ['panda'] },
  { emoji: '🐨', names: ['koala'] },
  { emoji: '🐵', names: ['monkey'] },
  { emoji: '🐸', names: ['frog'] },
  { emoji: '🐷', names: ['pig'] },
  { emoji: '🐮', names: ['cow'] },
  { emoji: '🦄', names: ['unicorn'] },
  { emoji: '🦋', names: ['butterfly'] },
  { emoji: '🐝', names: ['bee'] },
  { emoji: '🐢', names: ['turtle'] },
  { emoji: '🐟', names: ['fish'] },
  { emoji: '🐳', names: ['whale'] },
  { emoji: '🦖', names: ['dinosaur'] },
  { emoji: '🌸', names: ['flower'] },
  { emoji: '🌹', names: ['rose'] },
  { emoji: '🌻', names: ['sunflower'] },
  { emoji: '🌵', names: ['cactus'] },
  { emoji: '🌳', names: ['tree'] },
]

export type EmojiEntry = (typeof EMOJI_CATALOGUE)[number]

export function normalizeEmojiQuery(query: string): string {
  return query.toLowerCase().replace(/_/g, '-')
}

export function emojiMatches(query: string): EmojiEntry[] {
  const needle = normalizeEmojiQuery(query)
  return needle
    ? EMOJI_CATALOGUE.filter(({ names }) => names.some((name) => name.includes(needle)))
    : [...EMOJI_CATALOGUE]
}

export function emojiForName(name: string): string | undefined {
  return EMOJI_CATALOGUE.find((entry) => entry.names.includes(normalizeEmojiQuery(name)))?.emoji
}
